# Generated by Django 4.0 on 2021-12-31 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('cataloge', '0009_alter_trainingrequest_status'),
        ('empBoard', '0002_remove_messages_reason_messages_result_messages_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTrainings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cataloge.training')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
