# Generated by Django 4.0 on 2021-12-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cataloge', '0005_trainingrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingrequest',
            name='status',
            field=models.CharField(max_length=1, null=True, verbose_name='status'),
        ),
    ]
