# Generated by Django 4.0 on 2021-12-31 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cataloge', '0009_alter_trainingrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='participants',
            field=models.IntegerField(default=0),
        ),
    ]
