# Generated by Django 4.0 on 2021-12-31 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cataloge', '0010_training_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='trainings_nb',
            field=models.IntegerField(default=0),
        ),
    ]
