# Generated by Django 4.0 on 2021-12-28 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_employee_email_alter_employee_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='EmployeeRegisterRequest',
        ),
    ]
