# Generated by Django 4.0 on 2021-12-29 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cataloge', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='name',
        ),
        migrations.AddField(
            model_name='training',
            name='content',
            field=models.FileField(max_length=255, null=True, upload_to=None, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='training',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cataloge.organization'),
        ),
        migrations.AddField(
            model_name='training',
            name='title',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(default='tet', max_length=200, verbose_name='Name'),
        ),
    ]
