# Generated by Django 4.0 on 2021-12-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cataloge', '0003_alter_training_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='requests',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
    ]
