# Generated by Django 4.0 on 2021-12-30 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cataloge', '0008_alter_trainingrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingrequest',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
