# Generated by Django 4.0 on 2021-12-30 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_name', models.CharField(max_length=200)),
                ('content_url', models.URLField(verbose_name='url')),
                ('reason', models.TextField(verbose_name='reason')),
            ],
        ),
    ]
