# Generated by Django 4.0 on 2021-12-31 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empBoard', '0003_usertrainings'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertrainings',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
